spring.cloud.stream.bindings.output.contentType: application/json
spring.cloud.stream.kstream.binder.configuration.commit.interval.ms: 1000
spring.cloud.stream.kstream.binder.configuration:
  key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.bindings.output:
  destination: counts
  producer:
    headerMode: raw
    useNativeEncoding: true
spring.cloud.stream.bindings.input:
  destination: words
  consumer:
    headerMode: raw
spring.cloud.stream.kstream.binder:
  brokers: 192.168.99.100
  zkNodes: 192.168.99.100