== What is this app?

This app is used to run throughput performance tests on Spring Cloud Stream consumer against the Kafka binder.

It allows the testing of two different usage patterns of StreamListener (one is a delcarative approach where we declaratively handle the input message and the other one is a non declarative approach which means that on each message arrival at the input channnel, target method arguments are resolved and then invoke the method)

=== Before running the app, make sure that you have Kafka environment up and running. Use one of the following methods

1. You can use a local Kafka cluster (single node clusters are enough)
2. Or a fdull blown Kafka cluster somewhere on powerful servers or platforms (GCP, AWS, Rackspace etc.)
3. Or you can also run Kafka inside a docker ennvironment. For this go to the docker directory in this repo and invoke the command `docker-compose up -d`.
   
Once you have a kafka environment, do the following.

1. Go to your kafka home. If you are using the docker images, invoke the script `start-kafka-shell.sh` and then `cd $KAFKA_HOME`.


* zookeeper-ip below is localhost on linux or 192.168.99.100 on mac osx.

bin/kafka-topics.sh --zookeeper 192.168.99.100:2181 --create --topic foobar --partitions 3 --replication-factor 1
bin/kafka-topics.sh --zookeeper 192.168.99.100:2181 --describe foobar

Pre-load 1 million messages with 1K size:

bin/kafka-producer-perf-test.sh --num-records 1000000 --record-size 1024 --producer-props bootstrap.servers=192.168.99.100:9092 zk.connect=192.168.99.100:2181 batch.size=100  --throughput 100000 --topic foobar

java -jar scst-kafka-perf-0.0.1-SNAPSHOT.jar --spring.cloud.stream.kafka.binder.brokers=192.168.99.100 --spring.cloud.stream.kafka.binder.zkNodes=192.168.99.100 --non.declarative=true --num.messages=1000000 --print.on.every=10000 --spring.cloud.stream.bindings.input.destination=foobar --spring.kafka.consumer.groupId=scst-foo-4

